apiVersion: v1
kind: Service
metadata:
  name: rampup-demo
  labels:
    app: rampup-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
  selector:
    app: rampup-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rampup-demo
  labels:
    app: rampup-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rampup-demo
  template:
    metadata:
      labels:
        app: rampup-demo
    spec:
      containers:
      - name: rampup-demo
        image: 192.168.73.138:5000/demo:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 0.5Gi
          requests:
            cpu: 200m
            memory: 0.2Gi
